Added env specfic job with different branch

diff --git a/.github/workflows/ai.yml b/.github/workflows/ai.yml
--- a/.github/workflows/ai.yml
+++ b/.github/workflows/ai.yml
@@ -1,8 +1,9 @@
 name: ai CI/CD
 
 on:
+
   push:
-    branches: [main]
+    branches: [main,dev]
     paths:
       - 'ai/**'   # Only run if ai changes
   workflow_dispatch:
@@ -10,7 +11,6 @@ on:
 jobs:
   build-and-test:
     runs-on: ubuntu-latest
-
     steps:
       - uses: actions/checkout@v4
 
@@ -25,10 +25,59 @@ jobs:
           docker stop test-ai
           docker rm test-ai
 
-  deploy:
+  deploy-dev:
     runs-on: ubuntu-latest
     needs: build-and-test   # won't run if build fails
+    environment:
+      name: dev
+    steps:
+      - uses: actions/checkout@v4
 
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ap-south-1
+
+      - name: Deploy via SSM
+        run: |
+          BRANCH="${{ github.ref_name }}"
+          COMMAND_ID=$(aws ssm send-command \
+            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
+            --document-name "AWS-RunShellScript" \
+            --parameters 'commands=[
+              "cd /opt/payroll-app/ai",
+              "git pull origin '"$BRANCH"'",
+              "docker build -t ai:latest .",
+              "docker stop ai || true",
+              "docker rm ai || true",
+              "docker run -d -p 5000:5000 --name ai ai:latest",
+              "sleep 5",
+              "curl -f http://localhost:5000"
+            ]' \
+            --query "Command.CommandId" \
+            --output text)
+
+          aws ssm wait command-executed \
+            --command-id "$COMMAND_ID" \
+            --instance-id ${{ secrets.EC2_INSTANCE_ID }}
+
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
+            --query "Status" \
+            --output text)
+
+          echo "Deployment status: $STATUS"
+          [ "$STATUS" = "Success" ] || exit 1
+
+  deploy-prod:
+    runs-on: ubuntu-latest
+    needs: deploy-dev # won't run if build fails
+    if: github.ref == 'refs/heads/main'   
+    environment:
+      name: production
     steps:
       - uses: actions/checkout@v4
 
diff --git a/.github/workflows/fronend.yml b/.github/workflows/fronend.yml
--- a/.github/workflows/fronend.yml
+++ b/.github/workflows/fronend.yml
@@ -2,7 +2,7 @@ name: frontend CI/CD
 
 on:
   push:
-    branches: [main]
+    branches: [main,dev]
     paths:
       - 'frontend/**'   # Only run if frontend changes
   workflow_dispatch:
@@ -25,9 +25,59 @@ jobs:
           docker stop test-frontend
           docker rm test-frontend
 
-  deploy:
+  deploy-dev:
     runs-on: ubuntu-latest
     needs: build-and-test   # won't run if build fails
+    environment: dev
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ap-south-1
+
+      - name: Deploy via SSM
+        run: |
+          BRANCH="${{ github.ref_name }}"
+          COMMAND_ID=$(aws ssm send-command \
+            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
+            --document-name "AWS-RunShellScript" \
+            --parameters 'commands=[
+              "cd /opt/payroll-app/frontend",
+              "git pull origin '"$BRANCH"'",
+              "docker build -t frontend:latest .",
+              "docker stop frontend || true",
+              "docker rm frontend || true",
+              "docker run -d -p 8080:80 --name frontend frontend:latest",
+              "sleep 5",
+              "curl -f http://localhost:8080"
+            ]' \
+            --query "Command.CommandId" \
+            --output text)
+
+          aws ssm wait command-executed \
+            --command-id "$COMMAND_ID" \
+            --instance-id ${{ secrets.EC2_INSTANCE_ID }}
+
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
+            --query "Status" \
+            --output text)
+
+          echo "Deployment status: $STATUS"
+          [ "$STATUS" = "Success" ] || exit 1
+
+  deploy-prod:
+    runs-on: ubuntu-latest
+    needs: deploy-dev # won't run if build fails
+    if: github.ref == 'refs/heads/main'
+    environment:
+      name: production
 
     steps:
       - uses: actions/checkout@v4
